name: E2e Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
      options: --user 1001

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install --frozen-lockfile

    - name: Inject environment variables
      run: |
        rm -f example/.env
        echo "VITE_BUCKETEER_API_KEY=${{ secrets.E2E_API_KEY }}" >> example/.env
        echo "VITE_BUCKETEER_API_ENDPOINT=${{ secrets.E2E_API_ENDPOINT }}" >> example/.env
        echo "CI=true" >> example/.env

    - name: Build
      run: |
        pnpm run build
        pnpm run example:build

    - name: Run E2e tests
      run: |
        pnpm exec playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
