name: E2e Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Inject environment variables
      run: |
        rm -f example/.env
        echo "VITE_BUCKETEER_API_KEY=${{ secrets.E2E_API_KEY }}" >> example/.env
        echo "VITE_BUCKETEER_API_ENDPOINT=${{ secrets.E2E_API_ENDPOINT }}" >> example/.env
        echo "CI=true" >> example/.env
    - name: Build
      run: |
        pnpm run build
        pnpm run example:build
    - name: Run E2e tests
      run: |
        pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: e2e-report
        path: e2e-report/
        retention-days: 30
